name: netcdf_dggs_converter
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.9
  
  # Core scientific computing
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  
  # Geospatial libraries
  - geopandas>=0.12.0
  - shapely>=1.8.0
  - fiona>=1.8.0
  - pyproj>=3.3.0
  
  # Raster processing
  - rasterio>=1.3.0
  - xarray>=2022.6.0
  - netcdf4>=1.6.0
  
  # Additional dependencies
  - gdal>=3.4.0
  - proj>=9.0.0
  - geos>=3.10.0
  
  # Optional but recommended for performance
  - numba>=0.56.0
  - dask>=2022.6.0
  
  # Development and testing (optional)
  - jupyter
  - ipython
  - matplotlib
  - seaborn
  
  # Pip dependencies
  - pip
  - pip:
    - dggal